name: Nix stuff

on:
  push: {}

jobs:
  devshell:
    strategy:
      fail-fast: false
      matrix:
        runsOn:
          - ubuntu-24.04
          - macos-13
          - macos-15
    runs-on: ${{ matrix.runsOn }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v15
        with:
          name: macalinao
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix -Lv flake check --show-trace
      - run: nix -Lv develop -c echo OK
